### ISSUE TITLE
각 페이지별 rater 추가

### ISSUE THREAD

**Issue by Fine-Tuner** [coolchaeyoung/All_Review_You#13]
- [x] : 메인 페이지
- [x] : 마이 페이지
- [x] : 리뷰 상세 페이지
- [x] : 리뷰 작성 페이지

**Comment by piggmme** [comment]
- outline 변경
- header => margin-bottom
- 리뷰 메인 흰색 배경 넣기
- 리뷰 메인 패딩 , 폰트 크기 변경
- aside => section

**Comment by Fine-Tuner** [comment]
> * outline 변경
> * header => margin-bottom
> * 리뷰 메인 흰색 배경 넣기
> * 리뷰 메인 패딩 , 폰트 크기 변경
> * aside => section

반영하였습니다.
