### ISSUE TITLE
리뷰 상세 페이지 - 좋아요 수정

### ISSUE THREAD

**Issue by Fine-Tuner** [coolchaeyoung/All_Review_You#21]
- [x] : 좋아요 반응되게 수정

**Comment by piggmme** [comment]
- [ ] 좋아요 처리가 클래스 명이 달라서 해결이 안됨. 클래스 명을 추가해도 잘 안되는거 보면 해결이 필요함
 @joker77z

**Comment by Fine-Tuner** [comment]
> * [ ]  좋아요 처리가 클래스 명이 달라서 해결이 안됨. 클래스 명을 추가해도 잘 안되는거 보면 해결이 필요함
>   @joker77z

넵
