### ISSUE TITLE
공통 - Star 찍기

### ISSUE THREAD

**Issue by piggmme** [coolchaeyoung/All_Review_You#27]
## 참고 링크
[npmjs.com/package/rater-js](https://www.npmjs.com/package/rater-js)

## JS

- [x] rater.js 공부하기
- [x] rater.js

**Comment by piggmme** [comment]
@joker77z

**Comment by Fine-Tuner** [comment]
> @joker77z

rater-js 리뷰 작성 페이지 제외 적용되었습니다.
리뷰 작성 페이지 추후 적용 예정입니다.
