### ISSUE TITLE
인프라 구축 - DB Mockup 데이터 만들기

### ISSUE THREAD

**Issue by jkpark104** [coolchaeyoung/All_Review_You#8]
- 블로그의 구성요소인 User(사용자) Review(게시글), Comment(답글)에 대한 상태를 저장하는 데이터 스키마 만들기
- [x] User Data_Schema 구현
- [x] Review Data_Schema 구현
- [x] Comment Data_Schema 구현

**Comment by Fine-Tuner** [comment]
참여하겠습니다.

**Comment by piggmme** [comment]
참여하겠습니다
